### ISSUE TITLE
WMI_Query.groovy Syntax/Compilation error

### ISSUE THREAD

**Issue by pcarpenterdba** [logicmonitor/monitoring-recipes#23]
wmi_output_all is a list of maps, not a map itself so the code gives a compilation error for the following line

wmi_output_all.each { k, v ->

it should be 

wmi_output_first.each { k, v ->

or an embedded loop

wmi_output_all.each{entry ->
    entry.each { k,v ->

        // print k=v
        println "${k}=${v}"
    }
}

**Comment by akitsen** [comment]
Fixed in master

**Comment by akitsen** [comment]
Thanks for catching that @pcarpenterdba
